openapi: 3.0.1
info:
  title: monster-manticore
  x-cortex-tag: monster-manticore
  x-cortex-custom-metadata:
    alignment: neutral
    type: undead
    challenge_rating: 3
    legendary: false
    armor_class: 20
    hit_points: 57
    source: dnd-5e
  x-cortex-type: monster
  x-cortex-git:
    github:
      repository: xycia-cortex/monster-manticore
      alias: github-token-test
